#!/bin/bash

while read <&10 remote_ip; do
    ssh $remote_ip "[[ ! -rd $1 ]] && sudo mkdir $1; sudo chmod 777 $1;"
    rsync -avzh --chmod=ugo=rwx $1/* $remote_ip:$1
    echo -e "---- 同步 $remote_ip:$1 完成----\n"
done 10< $2

